Document: happah-core
Title: Debian happah-core Manual
Author: <insert document author here>
Abstract: This manual describes what happah-core is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/happah-core/happah-core.sgml.gz

Format: postscript
Files: /usr/share/doc/happah-core/happah-core.ps.gz

Format: text
Files: /usr/share/doc/happah-core/happah-core.text.gz

Format: HTML
Index: /usr/share/doc/happah-core/html/index.html
Files: /usr/share/doc/happah-core/html/*.html
